version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_aws
    versions:
    - 2.1.6
    - 2.1.7
    - 2.1.8
    - 2.1.9
    - 2.2.0
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
    - 4.9.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@reach/combobox"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
    - 0.15.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: purgecss-webpack-plugin
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: mapbox-gl
    versions:
    - 1.13.1
    - 2.0.1
    - 2.1.0
    - 2.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
