language: elixir

elixir: "1.9.0"

addons:
    postgresql: '9.4'

services:
    - postgresql

before_script:
    - mix do ecto.create, ecto.migrate

script:
    - mix test

cache:
    directories:
        - _build
        - deps
